# Generated by Django 3.0.1 on 2020-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
